### ISSUE TITLE
图片缩放变成100%，发现底部会出现下拉框

### ISSUE THREAD

**Issue by fantasy1943** [wangeditor-team/server#2]
http://127.0.0.1:3000/html/upload-image.html

**Comment by wangfupeng1988** [comment]
> http://127.0.0.1:3000/html/upload-image.html

你本地的 url ，我访问不了

**Comment by wangfupeng1988** [comment]
> 图片缩放变成100%，发现底部会出现下拉框

去 https://github.com/wangeditor-team/wangEditor/issues 提交问题吧

**Comment by Greenjiao** [comment]
> > http://127.0.0.1:3000/html/upload-image.html
> 
> 你本地的 url ，我访问不了

没绷住，笑出声哈哈哈哈
